### ISSUE TITLE
Dependencies for `./styleguide` are missing

### ISSUE THREAD

**Issue by roschaefer** [appinteractive/HC-WebApp#1]
I don't know what exactly the goal of `yarn run styleguide:build` is. But when I do `yarn install` the postinstall is not run. So why not put instructions in the README?

```sh
# Install dependencies
yarn install
cd ./styleguide
yarn install
```

**Comment by appinteractive** [comment]
There was an issue with a dependency which prevented the installation. Could you try again with the latest version and the command `yarn install --ignore-engines`?

**Comment by appinteractive** [comment]
See info at https://docs.human-connection.org/nitro/ui/installation

**Comment by roschaefer** [comment]
I solved that problem in the `docker` branch. You simply never install dependencies for `./styleguide`. Has nothing to do with `--ignore-engines`. I updated the README.

**Comment by appinteractive** [comment]
Ups 😬, yeah I’m not do happy with the Post install anyway as it always runs but that might be a good problem preventer.

**Comment by appinteractive** [comment]
added it to the readme's
